create resources as root to make multiple deployments possible
cozy-hosting/snug pull request #11
Opened 2021-03-23 20:54 UTC by Tim-Obert

add publish block to publish ports and domains
add loadBalancer block
Closes #10

2021-03-23 20:55 UTC, Tim-Obert commented on src/script/data/Domain.kt
> +    val host: String
maybe we need a better naming there

2021-03-23 20:58 UTC, Tim-Obert commented on src/script/data/PublishDomains.kt
> +    var domains: Set<Domain>
Not sure with the naming here. The current syntax would create sth. like:
` "publish": {
                "ports": [
                    {
                        "port": 8080
                    }
                ],
                "domains": [
                            {
                                "host": "oechsler.it"
                            }
                        ]
                    }
                ]
            }`

2021-03-28 12:55 UTC, oechsler requested changes

2021-03-28 12:55 UTC, oechsler commented on src/script/data/Resources.kt
> +}
This can be removed ...

2021-03-28 12:55 UTC, oechsler commented on src/script/language/DeploymentBuilder.kt
>      }
Maybe put this to the end off the class for consistency reasons

2021-03-28 12:55 UTC, oechsler commented on src/script/language/PublishDomainBuilder.kt
> +
?

2021-03-28 12:55 UTC, oechsler commented on src/script/language/ResourcesBuilder.kt
> +    }
This should only process the other `ScriptRoot` instances that it holds

2021-03-28 21:05 UTC, oechsler commented on src/script/data/Resources.kt
> +)
Isn't it possible to remove this now?

2021-03-28 21:06 UTC, oechsler reviewed
Make sure that if `Resources.kt` is not needed anymore to remove it. Other than that, this PR is approved!

2021-03-28 21:07 UTC, oechsler approved these changes

2021-03-28 21:09 UTC, merged